"""start bd

Revision ID: 00fff9aae2bd
Revises: 
Create Date: 2025-05-08 19:20:50.869924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00fff9aae2bd'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Products',
    sa.Column('ProductID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Price', sa.Float(), nullable=False),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('ProductID')
    )
    op.create_table('Users',
    sa.Column('UsersID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('Name', sa.String(length=100), nullable=False),
    sa.Column('Surname', sa.String(length=100), nullable=False),
    sa.Column('Patronymic', sa.String(length=100), nullable=True),
    sa.Column('Login', sa.String(length=50), nullable=False),
    sa.Column('Password', sa.String(length=255), nullable=False),
    sa.Column('Photo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('UsersID'),
    sa.UniqueConstraint('Login')
    )
    op.create_table('Baskets',
    sa.Column('BasketID', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('UsersID', sa.Integer(), nullable=False),
    sa.Column('ProductID', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ProductID'], ['Products.ProductID'], ),
    sa.ForeignKeyConstraint(['UsersID'], ['Users.UsersID'], ),
    sa.PrimaryKeyConstraint('BasketID')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Baskets')
    op.drop_table('Users')
    op.drop_table('Products')
    # ### end Alembic commands ###
